import { signIn, useSession } from 'next-auth/react';
import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          {session && JSON.stringify(session)}
        </div>
      </main>
    </>
  );
};

export default Home;
